ifndef NEURAL_MODELLING_DIRS
    $(error NEURAL_MODELLING_DIRS is not set.  Please define NEURAL_MODELLING_DIRS (possibly by running "source setup" in the neural_modelling folder within the sPyNNaker source folder))
endif

MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CURRENT_DIR := $(dir $(MAKEFILE_PATH))
EXTRA_SRC_DIR := $(abspath $(CURRENT_DIR))
APP_OUTPUT_DIR := $(abspath $(CURRENT_DIR)../../spynnaker_extra_pynn_models/model_binaries/)/
CFLAGS += -I$(NEURAL_MODELLING_DIRS)/src

EXTRA_SYNAPSE_TYPE_OBJECTS += 
                       
EXTRA_STDP += $(BUILD_DIR)neuron/plasticity/stdp/synapse_dynamics_stdp_target_impl.o

EXTRA_STDP_WEIGHT_DEPENDENCE += 

EXTRA_STDP_TIMING_DEPENDENCE += $(BUILD_DIR)neuron/plasticity/stdp/timing_dependence/timing_target_pair_impl.o \
                                $(BUILD_DIR)neuron/plasticity/stdp/timing_dependence/timing_recurrent_pre_stochastic_impl.o\
                                $(BUILD_DIR)neuron/plasticity/stdp/timing_dependence/timing_recurrent_dual_fsm_impl.o\
                                $(BUILD_DIR)neuron/plasticity/stdp/timing_dependence/timing_vogels_2011_impl.o

include $(NEURAL_MODELLING_DIRS)/src/neuron/builds/Makefile.common
